#!/usr/bin/env perl
# ALSA MIDI filter
# Copyright 2013  Jim Cochrane - GNU GPL, verson 2

use Modern::Perl;
use constant::boolean;
use Data::Dumper;
use Carp;

use MIDI_EventStream;
use AppConfiguration;

my $app = AppConfiguration->new();
$app->debug();
my $stream = $app->midi_stream();

say "starting ", $app->application_name();
say "app verbose: ", ($app->verbose()? 'yes': 'no');
$stream->process();
